Repository GDAEON/InGameHero, pull requests merged in 2022-01, with the labels that each got.

#54 Minor improvements
  Assets/Enemies/Scripts/EnemyController.cs
  Assets/Player/Scripts/Controller.cs
Labels: help wanted

#55 Workaround for audiolistener
  Assets/Player/Scripts/Controller.cs
Labels: bug

#58 Fixed
  .gitignore
  Assets/Player/Scripts/Controller.cs
Labels: bug

#61 Gd 118 bug teleportation attempts
  Assets/Player/Scripts/Controller.cs
  UserSettings/EditorUserSettings.asset
Labels: invalid

#64 GD-161 now you can't transmit to dead body Closes #60
  Assets/Enemies/Scripts/EnemyController.cs
  Assets/Player/Scripts/Controller.cs
  UserSettings/EditorUserSettings.asset
Labels: invalid

#68 Done
  Assets/Pickups.meta
  Assets/Pickups/Prefabs.meta
  Assets/Pickups/Prefabs/AID.prefab
  Assets/Pickups/Prefabs/AID.prefab.meta
  Assets/Pickups/Prefabs/BonusStamina.prefab
  Assets/Pickups/Prefabs/BonusStamina.prefab.meta
  Assets/Pickups/Prefabs/BonusTime.prefab
  Assets/Pickups/Prefabs/BonusTime.prefab.meta
  Assets/Pickups/Scripts.meta
  Assets/Pickups/Scripts/FAK.cs
  Assets/Pickups/Scripts/FAK.cs.meta
  Assets/Pickups/Scripts/StaminaPickup.cs
  Assets/Pickups/Scripts/StaminaPickup.cs.meta
  Assets/Pickups/Scripts/TimePickup.cs
  Assets/Pickups/Scripts/TimePickup.cs.meta
  Assets/Player/Scripts/Controller.cs
  Assets/Scenes/LVL1/LVL1.unity
Labels: enhancement

#70 GD-132 added help bot
  Assets/Friendly Entities.meta
  Assets/Friendly Entities/HelpBot.meta
  Assets/Friendly Entities/HelpBot/Animations.meta
  Assets/Friendly Entities/HelpBot/Animations/Plane_PlaneAction.001.anim
  Assets/Friendly Entities/HelpBot/Animations/Plane_PlaneAction.001.anim.meta
  Assets/Friendly Entities/HelpBot/Animations/SphereAnimation.anim
  Assets/Friendly Entities/HelpBot/Animations/SphereAnimation.anim.meta
  Assets/Friendly Entities/HelpBot/Materials.meta
  Assets/Friendly Entities/HelpBot/Materials/Материал.mat
  Assets/Friendly Entities/HelpBot/Materials/Материал.mat.meta
  Assets/Friendly Entities/HelpBot/Prefabs.meta
  Assets/Friendly Entities/HelpBot/Prefabs/GD-83 v5.prefab
  Assets/Friendly Entities/HelpBot/Prefabs/GD-83 v5.prefab.meta
  Assets/Friendly Entities/HelpBot/Source.meta
  Assets/Friendly Entities/HelpBot/Source/GD-83 v5.fbx
  Assets/Friendly Entities/HelpBot/Source/GD-83 v5.fbx.meta
  Assets/Scenes/PreLVL/PreLVL.unity
Labels: enhancement
